import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build directory of the integration test server; generated code, not ours.
    ".next-test/**",
    // Written by a Playwright or a coverage run. They are gitignored, but eslint
    // reads the working tree, so anyone who has run the e2e suite once was
    // linting a few thousand lines of bundled report viewer.
    "playwright-report/**",
    "test-results/**",
    "blob-report/**",
    "coverage/**",
    // Generated by prisma generate.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
