import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build directory of the integration test server; generated code, not ours.
    ".next-test/**",
    // Generated by prisma generate.
    "src/generated/**",
    // Design handoff bundle from claude.ai/design: a prototype we read, not
    // code we ship or maintain.
    "docs/design/**",
  ]),
]);

export default eslintConfig;
